import { Database } from "@/integrations/supabase/types";

type USTARating = Database["public"]["Enums"]["usta_rating"];

export type Player = {
  id: string;
  firstName: string;
  lastName: string;
  cellNumber: string;
  ustaRating: USTARating;
};

import React, { useState } from "react";
import { toast } from "sonner";

type PlayerFormProps = {
  onAddPlayer: (player: Player) => void;
};

export const PlayerForm: React.FC<PlayerFormProps> = ({ onAddPlayer }) => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [cellNumber, setCellNumber] = useState("");
  const [ustaRating, setUstaRating] = useState<USTARating>("2.5C"); // Default value

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newPlayer: Player = {
      id: "", // ID will be generated by Supabase
      firstName,
      lastName,
      cellNumber,
      ustaRating,
    };
    onAddPlayer(newPlayer);
    setFirstName("");
    setLastName("");
    setCellNumber("");
    setUstaRating("2.5C"); // Reset to default
    toast.success("Player added successfully!");
  };

  return (
    <form onSubmit={handleSubmit} className="mb-4">
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <input
          type="text"
          placeholder="First Name"
          value={firstName}
          onChange={(e) => setFirstName(e.target.value)}
          required
          className="border p-2"
        />
        <input
          type="text"
          placeholder="Last Name"
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
          required
          className="border p-2"
        />
        <input
          type="text"
          placeholder="Cell Number"
          value={cellNumber}
          onChange={(e) => setCellNumber(e.target.value)}
          required
          className="border p-2"
        />
        <select
          value={ustaRating}
          onChange={(e) => setUstaRating(e.target.value as USTARating)}
          className="border p-2"
        >
          <option value="2.5C">2.5C</option>
          <option value="3.0A">3.0A</option>
          <option value="3.0C">3.0C</option>
          <option value="3.5A">3.5A</option>
          <option value="3.5C">3.5C</option>
          <option value="4.0A">4.0A</option>
          <option value="4.0C">4.0C</option>
          <option value="4.5A">4.5A</option>
          <option value="4.5C">4.5C</option>
          <option value="5.0A">5.0A</option>
          <option value="5.0C">5.0C</option>
        </select>
      </div>
      <button type="submit" className="mt-4 bg-blue-500 text-white p-2">
        Add Player
      </button>
    </form>
  );
};
